app_form4validacionregistro:
    resource: "@AppBundle/Resources/config/routing/form4validacionregistro.yml"
    prefix:   /form4validacionregistro

app_formulario2:
    resource: "@AppBundle/Resources/config/routing/formulario2.yml"
    prefix:   /formulario2

